buildlimit: 100
instlimit: -1
memlimit: 512
path:
  compiler: /home/compiler-vm/Desktop/Compiler-Lite
  dataset: /home/compiler-vm/Desktop/Compiler-Lite/test/Compiler-2020-testcases
  simulator: /home/compiler-vm/Desktop/Compiler-Lite/ravel/build/src
  simulator-executable: /home/compiler-vm/Desktop/Compiler-Lite/ravel/build/src/ravel
  built-in: /home/compiler-vm/Desktop/Compiler-Lite/test/builtin.s
stage: semantic
timelimit: 15
